### ISSUE TITLE
Release the Gem of version 0.1.1

### ISSUE THREAD

**Issue by jackypan000** [SOA-Upstart4/Team-HW-1-Ideate-and-Scrape#47]
1. Finalize the testing 
2. Create version.rb for Gem version control

**Comment by jackypan000** [comment]
@LeeTung-Yu  I can't assign both of you QQ

**Comment by LeeTung-Yu** [comment]
想問這個一次只能assign給一個人嗎？
我已將test部份補上，麻煩幫我檢查一下，可以的話請幫我merge，謝謝
子涵command interface也快要完成了！

**Comment by jackypan000** [comment]
只能Assign一個人耶....另一個人會被取消掉@@"
